### ISSUE TITLE
Migrate StackEye App to React JS

### ISSUE THREAD

**Issue by sachinjain024** [stackxyz/stackeye#42]
Items:
- [x] Setup React App with multiple routes for each User Notifications, Question Notifications, Users, Questions with empty/default content
- [x] Populate Data into each view
- [ ] Use ItemSelector to select items and use that as mixin. Move most of the common code there.
- [ ] Update count in each tab heading when items are removed.

Futuristic items:
- [ ] Implement Storage Service and publish that as npm package and use that

**Comment by kevin-brown** [comment]
Any particular reason why? There isn't much to this app, I'm surpised that React would be necessary.

**Comment by blunderboy** [comment]
@kevin-brown Thanks for bringing this up. Here are few points, 
- I wrote this app when I was learning web development and I think its current templating is not in good shape.
- I am going to provide more features in it like following Tags, Searching favorite list, following particular StackExchange sites for new questions. Current UI design and templating does not seem very friendly.

I thought of choosing Angular earlier but recently after investigating React, I feel it is very performance and new concept. Moving to React/angular/backbone will provide the code more flexibility and readability.

Do you see any problems in doing this ?
