### ISSUE TITLE
no more follow option with new stackexchange update? or is there still?

### ISSUE THREAD

**Issue by nicbentulan** [stackxyz/stackeye#68]
how do i follow now with the new stackexchange update?

**Comment by ashutoshjangle** [comment]
Or is there a way to add users without the follow button?

**Comment by ashutoshjangle** [comment]
I just discovered that you can go to system and import a json file to add a user yourself. I had no idea what a json file was but you can export your current list and get an idea of what it looks like and then make your own and import it.

**Comment by sachinjain024** [comment]
Hey, @nicbentulan Thanks for opening the issue & a quick reminder over the email. I will fix the issue soon.

**Comment by sachinjain024** [comment]
Hey @ashutoshjangle @nicbentulan -- I have uploaded the zip in Chrome Store. Google takes usually a couple of days to review. WIll give you a heads up once it is available so you can test at your end.

**Comment by sachinjain024** [comment]
@ashutoshjangle @nicbentulan The update is available in Chrome Store. Here's a screenshot of Follow button on the profile page
![image](https://user-images.githubusercontent.com/3108399/131078464-38bbb0da-c21f-47c4-862f-3d3ad613a8da.png)

Can we close this ticket now?

**Comment by nicbentulan** [comment]
there's also a follow in the activity. thanks!
